# ЛИСТАЙ НИЖЕ - ТАМ ИНФА ПРО ЗАЧЕТ 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use('ggplot')
np.random.seed(42)

In [71]:
# задача 1
# в каждом столбце найти минимальный элемент столбца в матрице (гарантируется один) и удалить строки (без for)

array = np.random.randint(-10, 10, size=(5, 5))
print(array)
ind = np.argmin(array,axis=0)
print("удаляем:")
print(ind)
print("получаем:")
array = np.delete(array,ind,axis=0)
print(array)

[[-6 -9 -5 -9  2]
 [ 0  0  5  0  8]
 [ 4  5  0  5 -3]
 [-7 -3 -7 -8 -8]
 [ 7  8  8 -6  7]]
удаляем:
[3 0 3 0 3]
получаем:
[[ 0  0  5  0  8]
 [ 4  5  0  5 -3]
 [ 7  8  8 -6  7]]


In [85]:
# задача 2 на хор!
# на вход подается массив одномерный n*m, m найти сумму элементов, индексы которых при делении на m дают остатки 0, 1, 2, 
array = np.random.randint(0, 10, size=(6))
m = 3
print(array, "\n")
array = array.reshape(-1, m)
sum_array = array.sum(axis=0)
print(sum_array)

[3 9 1 7 5 4] 

[10 14  5]


### Что спрашивали на самом зачете?
простые вопросы: 
1. np.nan и None отличие
2. np.array.size() и np.array.size отличие
3. еще про ооп и функциональный интерфейс в plt
4. iloc и loc зачем нужны, когда применяем
5. a.size и a.size()
6. np.nan, pd.nan, None
7. a.ndim и len(a.shape)

Задачи: 
1. Мне давал задачу удалить строки у матрицы с макс количеством нулей
2. среди элементов с нечетными номерами найдите наибольший элемент массива который делиться на 3
3. на вход подается массив одномерный n*m, m найти сумму элементов, индексы которых при делении на m дают остатки 0, 1, 2, 
4. в каждом столбце найти минимальный элемент столбца в матрице (гарантируется один) и удалить строки (без for)

Тем, у кого были хорошо написаны контесты давали делать гифки на отл, находятся в приложенной директории в zachet

In [ ]:
# Примеры кода для гифок:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
ax.set_aspect(1)

N = 64

points = ax.plot(np.linspace(-1, 1, N*4), np.linspace(-1, 1, N*4), '.')[0]

def step(t):
    x = np.sin(np.linspace(0, np.pi/2, N, endpoint=False).reshape(-1, 1) * t + np.pi/2 * np.arange(4).reshape(1, -1)).reshape(-1)
    y = np.cos(np.linspace(0, np.pi/2, N, endpoint=False).reshape(-1, 1) * t + np.pi/2 * np.arange(4).reshape(1, -1)).reshape(-1)
    points.set_data(x, y)

anim = FuncAnimation(fig, func=step, frames=np.linspace(-1, 1, 100), interval=1000/30)

plt.show()


In [ ]:
#Решения задач
# задача 1
# в каждом столбце найти минимальный элемент столбца в матрице (гарантируется один) и удалить строки (без for)

array = np.random.randint(-10, 10, size=(5, 5))
print(array)
ind = np.argmin(array,axis=0)
print("удаляем:")
print(ind)
print("получаем:")
array = np.delete(array,ind,axis=0)
print(array)

# задача 2 на хор
# на вход подается массив одномерный n*m, m найти сумму элементов, индексы которых при делении на m дают остатки 0, 1, 2, 
array = np.random.randint(0, 10, size=(6))
m = 3
print(array, "\n")
array = array.reshape(-1, m)
sum_array = array.sum(axis=0)
print(sum_array)